services:
  db:
    image: mysql:8
    container_name: healthcare_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthcare_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysql", "-h", "127.0.0.1", "-u", "root", "-proot", "-e", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  app:
    build: .
    container_name: healthcare_app
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=healthcare_db
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: >
      bash -c "python3 automation_runner.py & 
               streamlit run member4/app.py --server.port=8501 --server.address=0.0.0.0"

  train:
    build: .
    container_name: healthcare_trainer
    # 'profiles' ensures this ONLY runs when you explicitly call it
    profiles: ["manual"]
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=healthcare_db
    volumes:
      - .:/app
    command: python3 main.py

volumes:
  mysql_data:
